controllers/DataController.php
<?php

namespace app\controllers;

use app\models\Item;
use app\models\ItemInsertion;
use yii\web\HttpException;

class DataController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionCreate()
    {
        $request = \Yii::$app->request;

        if ($request->isPost) {

            $params = $request->getBodyParam('CreateForm');

            $model = new Item();
            $model->attributes = $params;
            $model->image = "images/1.png";
            $model->articul = "ART" . (time()+100000);

            if ($model->validate()) {
                if (!($model->save())) {
                    throw new HttpException(500, 'Database Error');
                }
            } else {
                throw new HttpException(500, 'Validation Error');
            }

            $insertions = json_decode($params['insertion']);

            if (count($insertions) > 0) {
                foreach ($insertions as $insertion) {
                    $ins = new ItemInsertion();
                    $ins->item_id = $model->id;
                    $ins->insertion_id = $insertion[0];
                    $ins->color = $insertion[2];
                    $ins->amount = $insertion[3];
                    $ins->weight = $insertion[4];
                    $ins->form = 1;

                    if ($ins->validate()) {
                        if (!($ins->save())) {
                            throw new HttpException(500, 'Database Error');
                        }
                    }
                }
            }
            return $this->goHome();
        }
    }


    public function actionDelete()
    {
        $request = \Yii::$app->request;

        $id = $request->get('id');

        $item = Item::findOne($id);

        if ($item->delete()) {
            return $this->goHome();
        } else {
            throw new HttpException(500, 'Deleting Error');
        }
    }

    public function actionEdit()
    {
        $request = \Yii::$app->request;
        if ($request->isPost) {
            $params = $request->getBodyParam('EditForm');
            $model = Item::findOne($params['id']);
            $model->attributes = $params;

            if ($model->validate()) {

                if ($model->save()) {
                    return $this->goHome();
                } else {
                    throw new HttpException(500, 'Database Error');
                }
            } else {
                throw new HttpException(400, 'Validation Error');
            }
        }
        return $this->goHome();
    }

    public function actionAjaxcreate()
    {

        $request = \Yii::$app->request;
        $insertion = json_decode($request->post('params'));
        $id = $request->post('id');

        $model = new ItemInsertion();

        // Ajax
        $model->insertion_id = (int)$insertion[0];
        $model->form = (int)$insertion[1];
        $model->color = $insertion[2];
        $model->amount = (int)$insertion[3];
        $model->weight = (int)$insertion[4];

        $model->item_id = $id;
        
        if ($model->validate()) {
            if ($model->save()) {
                return $model->id;
            } else {
                return json_encode($model->getErrors()) . " " . $insertion[2];
            }
        } else {
            throw new HttpException(500);
        }
    }

    public function actionAjaxdelete()
    {
        $request = \Yii::$app->request;
        $insertion = $request->post('id');

        $model = ItemInsertion::findOne($insertion);

        if ($model->delete()) {
            return $model->id . " deleted";
        } else {
            throw new HttpException(500);
        }
    }
}

controllers/StoreController.php
<?php

namespace app\controllers;

use app\models\CreateForm;
use app\models\EditForm;
use app\models\Item;
use app\models\ItemInsertion;
use app\models\Type;
use app\models\Tematic;
use app\models\Material;
use app\models\Insertion;
use yii\data\Pagination;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;

class StoreController extends \yii\web\Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionError()
    {
        $exception = \Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            return $this->render('error', ['exception' => $exception]);
        }
    }

    public function actionIndex()
    {
        $params = \Yii::$app->request->get();
        $query = Item::find();

        // Query
        if (!empty($params["insertion"])) {
            $query->withAssertion($params['insertion']);
        }
        if (!empty($params["min"])) {
            $query->withMin($params['min']);
        }
        if (!empty($params["max"])) {
            $query->withMin($params['max']);
        }


        $count = $query->count('id');

        $pagination = new Pagination([
            'defaultPageSize' => 8,
            'totalCount' => $count,
        ]);

        $items = $query
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        $insertions = Insertion::find()->all();

        return $this->render('index', [
            'items' => $items,
            'pagination' => $pagination,
            'insertions' => $insertions,
        ]);
    }

    public function actionView()
    {
        $request = \Yii::$app->request;

        $art = $request->get('id');

        $item = Item::findOne(['id' => $art]);

        $sizes = ArrayHelper::map($item->itemSizes, 'size', 'amount');

        if ($art != null) {
            return $this->renderAjax('view', [
                'get' => $art,
                'item' => $item,
                'sizes' => $sizes,
            ]);
        }
    }

    public function actionNew()
    {
        $model = new CreateForm();

        $materials = ArrayHelper::map(Material::find()->all(), 'id', 'title');
        $types = ArrayHelper::map(Type::find()->all(), 'id', 'title');
        $tematic = ArrayHelper::map(Tematic::find()->all(), 'id', 'title');

        $insertions = ArrayHelper::map(Insertion::find()->all(), 'id', 'title');

        return $this->render('new',
            [
                'model' => $model,
                'materials' => $materials,
                'types' => $types,
                'tematic' => $tematic,
                'insertions' => $insertions,
            ]);
    }

    public function actionEdit()
    {

        $request = \Yii::$app->request;
        $id = $request->get('id');
        $item = Item::findOne($id);

        if (!$item) {
            throw new NotFoundHttpException('Товар не найден');
        }

        $model = new EditForm();

        // Form
        $insertions = ArrayHelper::map(Insertion::find()->all(), 'id', 'title');
        $materials = ArrayHelper::map(Material::find()->all(), 'id', 'title');
        $types = ArrayHelper::map(Type::find()->all(), 'id', 'title');
        $tematic = ArrayHelper::map(Tematic::find()->all(), 'id', 'title');

        $item_insertions = ItemInsertion::find()
            ->asArray()
            ->where(['item_id' => $id])
            ->all();

        return $this->render('edit',
            [
                'model' => $model,
                'materials' => $materials,
                'types' => $types,
                'tematic' => $tematic,
                'insertions' => $insertions,
                'item' => $item,
                'item_insertions' => $item_insertions,
            ]);
    }
}

views/store/edit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\web\View;

$this->title = 'Редактировать';
$this->params['breadcrumbs'][] = $this->title;

/* @var $this yii\web\View */
/* @var $model app\models\CreateForm */
/* @var $form ActiveForm */

$this->registerJs(
    "var item_insertions = " . json_encode($item_insertions) . ";", View::POS_BEGIN, 'my-options');

$model->setAttributes($item->attributes, false);

?>
<div class="row">

    <h1>Редактировать</h1>

    <div class="col-md-12">

        <?php $form = ActiveForm::begin([
            'method' => 'post',
            'action' => Url::toRoute('data/edit'),
            'options' => ['enctype' => 'multipart/form-data'],
        ]); ?>

        <?= $form->field($model, 'title') ?>
        <?= $form->field($model, 'price')->input('number') ?>
        <?= $form->field($model, 'weight') ?>
        <?= $form->field($model, 'description')->textarea() ?>
        <?= $form->field($model, 'material_id')->dropDownList($materials) ?>
        <?= $form->field($model, 'type_id')->dropDownList($types) ?>
        <?= $form->field($model, 'tematic_id')->dropDownList($tematic) ?>

        <div class="form-group">
            <label for="exampleInputPassword1">Используемые вставки</label>
            <table class="table" id="include">
                <tr>
                    <td></td>
                    <td>
                        <?= $form->field($model, 'insertions')->dropDownList($insertions)->label(false) ?>
                    </td>
                    <td>
                        <select class="form-control value-form">
                            <option value="1" selected>Шар</option>
                            <option value="2">Овал</option>
                        </select>
                    </td>
                    <td>
                        <select class="form-control value-color">
                            <option value="white" selected>Белый</option>
                            <option value="yellow">Желтый</option>
                            <option value="red">Красный</option>
                            <option value="blue">Синий</option>
                            <option value="green">Зеленый</option>
                        </select>
                    </td>
                    <td>
                        <input class="form-control value-amount" type="number" placeholder="Количество">
                    </td>
                    <td>
                        <input class="form-control value-weight" type="number" placeholder="Вес">
                    </td>
                    <td>
                        <button class="btn" type="button" id="addInclude">Добавить</button>
                    </td>
                </tr>
            </table>
        </div>

        <input type="text" id="insertion" hidden>

        <?= $form->field($model, 'insertion')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'id')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'articul')->hiddenInput()->label(false) ?>


        <div class="form-group">
            <?= Html::submitButton('Редактировать', ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>
<script>

    var includes = [];
    var table = $('#include');

    function fillTable(items) {

        items.forEach(function (item, i, arr) {

            var field_material = $("#editform-insertions option").eq(item['insertion_id'] - 1).text();
            var form = $(".value-form option").eq(item['form']).text();
            var color = $(".value-color option[value='" + item['color'] + "']").text();

            var current = [item['id'], item['insertion_id'], item['insertion_id'], item['color'], item['amount'], item['weight']];
            includes.push(current);

            setInsertions();

            table.append('<tr><td class=".id">' + item['id'] + ' </td><td>' + field_material + '</td><td>' + form + '</td><td>' + color + '</td><td>' + item['amount'] + ' шт</td><td>' + item['weight'] + '</td><td><a class="btn btn-default remove"><span class="glyphicon glyphicon-trash"></span></a></td></tr>');
        });
    }

    function setInsertions() {
        $('#editform-insertion').val(JSON.stringify(includes));
    }

    fillTable(item_insertions);

    //    REMOVE ELEMENT

    table.on('click', '.remove', function () {

        var index = $(this).closest('tr').index();
        var id = $(this).parents('tr').find('td:first').text();
        var row = $(this).closest('tr');

        $.ajax({
            type: "POST",
            url: "<?= Url::toRoute('data/ajaxdelete') ?>",
            data: {id},
            cache: false,
            success: function (data) {

                row.remove();
            }
        });
    });

    //    ADD ELEMENT

    $('#addInclude').click(function () {

        var table = $('#include');

        var row = $(this).closest('tr');

        var inc = row.find('#editform-insertions').val();
        var incf = row.find('#editform-insertions   option:selected').text();
        // GET form and value
        var form = row.find('.value-form').val();
        var formf = row.find('.value-form option:selected').text();
        // GET color and value
        var color = row.find('.value-color').val();
        var colorf = row.find('.value-color option:selected').text();
        // amount
        var quantity = parseInt(row.find('.value-amount').val(), 10);
        // weight
        var weight = parseFloat(row.find('.value-weight').val());
        // ready
        var current = [inc, form, color, quantity, weight];

        $.ajax({
            type: "POST",
            url: "<?= Url::toRoute('data/ajaxcreate') ?>",
            data: {'params': JSON.stringify(current), id: <?= $model->id ?>},
            cache: false,
            success: function (data) {
                table.append('<tr><td>' + data + '</td><td class=".id">' + incf + ' </td><td>' + formf + '</td><td>' + colorf + '</td><td>' + quantity + ' шт</td><td>' + weight + '</td><td><a class="btn btn-default remove"><span class="glyphicon glyphicon-trash"></span></a></td></tr>');
            }
        });
    });
</script>

views/store/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>
    <p>
        <a href="<?= \yii\helpers\Url::toRoute('store/index') ?>">Вернуться на главную</a>
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/store/index.php
<?php
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\web\View;

$this->title = 'Каталог';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="row">

    <div class="col-lg-2">

        <h3>Вставки</h3>
        <p>Всего: <?= $pagination->totalCount ?></p>

        <ul class="nav">
            <li><a href="<?= Url::toRoute('store/index') ?>">Все</a></li>

            <?php

            foreach ($insertions as $ins) {
                echo '<li class="insertion"><a href="' . Url::toRoute(['store/index', 'insertion' => $ins->id]) . '">' . $ins->title . '</a></li>';
            }

            ?>
        </ul>

        <h3>Вес</h3>

        <form action="<?= Url::toRoute('store/index') ?>">

            <div class="form-group">
                <input type="number" name="min" class="form-control" placeholder="От"
                       value="<?= Yii::$app->request->get('min') ?>">
            </div>
            <div class="form-group">
                <input type="number" name="max" class="form-control" placeholder="До"
                       value="<?= Yii::$app->request->get('max') ?>">
            </div>

            <input type="hidden" name="insertion" value="<?= Yii::$app->request->get('insertion') ?>">

            <input type="submit" class="btn" value="Применить">
        </form>

    </div>
    <div class="col-lg-10">
        <?php foreach ($items as $item): ?>
            <div class="col-sm-3 col-md-3 col-lg-3">
                <div class="thumbnail">
                    <img src="<?= Html::encode("{$item->image}") ?>" alt="...">
                    <div class="caption">
                        <h3><?= Html::encode("{$item->title}") ?></h3>
                        <p><?= Html::encode("{$item->articul}") ?></p>
                        <p>Тематика: <?= Html::encode("{$item->tematic->title}") ?></p>
                        <a type="button " class="btn btn-primary btn-block" data-toggle="modal" data-target="#info"
                           id="modal-btn" rel="<?= $item->id ?>">
                            Купить
                            за <?= Html::encode("{$item->price}") ?> &#8381;
                        </a
                        <br><br>
                        <a class="btn btn-default" href="<?= Url::toRoute(['store/edit', 'id' => $item->id]) ?>"><span
                                class="glyphicon glyphicon-pencil   " aria-hidden="true"></span></a>
                        <a href="<?= Url::toRoute(['data/delete', 'id' => $item->id]) ?>" class="btn btn-default"
                           type="submit"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>

                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        <?= LinkPager::widget(['pagination' => $pagination]) ?>
    </div>
</div>

<div class="modal fade" id="info" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Инфо</h4>
            </div>
            <div class="modal-body" id="mod"></div>
        </div>
    </div>
</div>
<script>
    $(document).on('click', '#modal-btn', function () {
        var id = $(this).attr("rel");
        $.ajax({
            type: "GET",
            url: "<?= Url::toRoute('store/view') ?>",
            data: {'id': id},
            cache: false,
            success: function (data) {
                $("#mod").html(data).fadeIn(200);
            }
        });
    });
    $('li > a').each(function () {
        if ($(this).prop("href") === window.location.href) {
            $(this).parent().css("background-color", "#eee");
        }
    });
</script>

views/store/new.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

use yii\helpers\ArrayHelper;

$this->title = 'Добавить';
$this->params['breadcrumbs'][] = $this->title;

/* @var $this yii\web\View */
/* @var $model app\models\CreateForm */
/* @var $form ActiveForm */
?>

<div class="row">
    <h1>Добавить</h1>
    <div class="col-md-12">

        <?php $form = ActiveForm::begin([
            'method' => 'post',
            'action' => Url::toRoute('data/create'),
            'options' => ['enctype' => 'multipart/form-data'],
        ]); ?>

        <?= $form->field($model, 'title') ?>
        <?= $form->field($model, 'price')->input('number') ?>
        <?= $form->field($model, 'weight')->input('number') ?>
        <?= $form->field($model, 'description')->textarea() ?>
        <?= $form->field($model, 'material_id')->dropDownList($materials) ?>
        <?= $form->field($model, 'type_id')->dropDownList($types) ?>
        <?= $form->field($model, 'tematic_id')->dropDownList($tematic) ?>
        <?= $form->field($model, 'insertion')->hiddenInput()->label(false) ?>

        <div class="form-group">
            <label for="exampleInputPassword1">Используемые вставки</label>
            <table class="table" id="include">
                <tr>
                    <td>
                        <?= $form->field($model, 'insertions')->dropDownList($insertions)->label(false) ?>
                    </td>
                    <td>
                        <select class="form-control value-form">
                            <option value="1" selected>Шар</option>
                            <option value="2">Овал</option>
                        </select>
                    </td>
                    <td>
                        <select class="form-control value-color">
                            <option value="white" selected>Белый</option>
                            <option value="yellow">Желтый</option>
                            <option value="red">Красный</option>
                            <option value="blue">Синий</option>
                            <option value="green">Зеленый</option>
                        </select>
                    </td>
                    <td>
                        <input class="form-control value-amount" type="number" placeholder="Количество">
                    </td>
                    <td>
                        <input class="form-control value-weight" type="number" placeholder="Вес">
                    </td>
                    <td>
                        <button class="btn" type="button" id="addInclude">Добавить</button>
                    </td>
                </tr>
            </table>
        </div>

        <input type="text" id="insertion" hidden>

        <div class="form-group">
            <?= Html::submitButton('Добавить', ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>
<script>

    var includes = [];

    $("#include").on('click', '.remove', function () {

        var index = $(this).closest('tr').index();

        includes.splice(index - 1, 1);

        $('#createform-insertion').val(JSON.stringify(includes));

        $(this).closest('tr').remove();

    });


    $('#addInclude').click(function () {

        var row = $(this).closest('tr');

        var inc = row.find('#createform-insertions').val();
        var incf = row.find('#createform-insertions   option:selected').text();

        var form = row.find('.value-form').val();
        var formf = row.find('.value-form option:selected').text();

        var color = row.find('.value-color').val();
        var colorf = row.find('.value-color option:selected').text();

        var quantity = parseInt(row.find('.value-amount').val(), 10);
        var weight = parseFloat(row.find('.value-weight').val());
        var current = [inc, form, color, quantity, weight];

        if ((weight > 0) && (quantity > 0)) {
            includes.push(current);

            $('#createform-insertion').val(JSON.stringify(includes));

            var table = $('#include');

            row.find('.value-inc option:selected').prop('disabled', 'disabled');

            table.append('<tr><td>' + incf + '</td><td>' + formf + '</td><td>' + colorf + '</td><td>' + quantity + ' шт</td><td>' + weight + '</td><td><a class="btn btn-default remove"><span class="glyphicon glyphicon-trash"></span></a></td></tr>');

        }

    });
</script>

views/store/view.php
<?php

use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\ArrayHelper;

?>

<div class="container-fluid">
    <div class="row">
        <h1><?= $item->title ?></h1>
        <div class="col-lg-6">
            <img src="<?= $item->image ?>" alt="" width="100%">
        </div>
        <div class="col-lg-6">
            <p><?= $item->description ?></p>
            <table class="table">
                <tr>
                    <td>Цена</td>
                    <td><?= $item->price ?> &#8381;</td>
                </tr>
                <tr>
                    <td>Цена за грамм</td>
                    <td><?php if ($item->weight > 0) echo round($item->price / $item->weight) ?></td>
                </tr>
                <tr>
                    <td>Артикул</td>
                    <td><?= $item->articul ?></td>
                </tr>
                <tr>
                    <td>Вид</td>
                    <td><?= $item->type->title ?></td>
                </tr>
                <tr>
                    <td>Тематика</td>
                    <td><?= $item->tematic->title ?></td>
                </tr>
                <tr>
                    <td>Вставки</td>
                    <td>
                        <?php
                        if (count($item->itemInsertions) > 0) {

                            foreach ($item->itemInsertions as $insertion) {
                                $svg = '<svg width="32" height="32"><rect width="32" height="32" style="fill:' . $insertion->color . ';stroke-width:1;stroke:rgb(0,0,0);" /></svg>';
                                echo $insertion->insertion->title . ": " . $insertion->amount . " шт. по " . $insertion->weight . " гр. Цвет: " . $svg . " <br>";
                            }
                        } else {
                            echo "Без вставок";
                        }
                        ?>
                    </td>
                </tr>
                <tr>
                    <td>Размеры</td>
                    <td>
                        <?php
                        if ($sizes)
                            foreach ($sizes as $size => $amount)
                                print "<strong>$size</strong> ($amount шт)<br>";
                        else
                            print "Нет в наличии";
                        ?>
                    </td>
                </tr>
                <tr>
                    <td>Материал</td>
                    <td><?= $item->material->title ?></td>
                </tr>
                <tr>
                    <td>Вес</td>
                    <td><?= $item->weight ?> гр</td>
                </tr>
            </table>
        </div>
    </div>
</div>